version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/usr/src/app/apps/frontend
      - /usr/src/app/apps/frontend/node_modules
      - ./packages:/usr/src/app/packages
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./apps/backend/src:/usr/src/app/apps/backend/src
      - ./packages:/usr/src/app/packages
      - ./seed-data:/usr/src/app/seed-data
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    restart: unless-stopped
    command: mongod --config /etc/mongod.conf

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data: